apiVersion: batch/v1
kind: Job
metadata:
  name: workload-generator
spec:
  template:
    metadata:
      labels:
        app: workload-generator
    spec:
      containers:
        - name: producer
          volumeMounts:
            - name: payload-template
              mountPath: /runtime/payload
            - name: producer-config
              mountPath: /runtime/config
            - name: flink-input
              mountPath: /opt/flink/files
          env:
            - name: PAYLOAD_TEMPLATE
              value: /runtime/payload/payload.hbs
            - name: NUM_RECORDS
              value: "1000000"
            # Configuration if sending to file
            - name: BATCH
              value: "true"
            # Configuration if sending to Kafka
            - name: TOPIC
              value: txns
            - name: NUM_THREADS
              value: "10"
            - name: PRODUCER_CONFIG
              value: /runtime/config/producer.config
            - name: THROUGHPUT
              value: "1"
          image: workload-generator
          imagePullPolicy: Always
      restartPolicy: OnFailure
      volumes:
        - name: payload-template
          configMap:
            name: payload-template
        - name: producer-config
          configMap:
            name: producer-config
        - name: flink-input
          persistentVolumeClaim:
            claimName: flink-input